version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "@d$]8~q4B]}@BcL)"
      MYSQL_DATABASE: ObservabilityDB
      MYSQL_USER: myuser
      MYSQL_PASSWORD: "@d$]8~q4B]}@BcL)"
    ports:
      - 3306:80
    volumes:
      - ./DataBaseVolume/data:/var/lib/mysql

  app:
    container_name: api
    build:
      context: .
      dockerfile: ./Api_Metrics_With_Prometheus/Api_Metrics_With_Prometheus/Dockerfile
    ports:
      - 8090:80

  prometheus:
    build:
      context: .
      dockerfile: Dockerfile.prometheus
    container_name: prometheus
    ports:
      - 8091:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    build:
      context: .
      dockerfile: Dockerfile.grafana
    container_name: grafana
    ports:
      - 8092:3000
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus