version: '3'
services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile.sqlserver
    container_name: sqlserver
    hostname: sqlserver
    environment:
      MSSQL_SA_PASSWORD: "@d$]8~q4B]}@BcL)"
      ACCEPT_EULA: Y
      MSSQL_PID: "Express"
    ports:
      - 1433:1433
    volumes:
      - ./DataBaseVolume/data:/var/opt/mssql/data

  app:
    container_name: api
    build:
      context: .
      dockerfile: ./Api_Metrics_With_Prometheus/Api_Metrics_With_Prometheus/Dockerfile
    ports:
      - 8090:80

  prometheus:
    build:
      context: .
      dockerfile: Dockerfile.prometheus
    container_name: prometheus
    ports:
      - 8091:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    build:
      context: .
      dockerfile: Dockerfile.grafana
    container_name: grafana
    ports:
      - 8092:3000
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus